//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/ControlPacket.msg.
//

#ifndef __CONTROLPACKET_M_H
#define __CONTROLPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ControlPacket;
/**
 * Class generated from <tt>messages/ControlPacket.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet ControlPacket
 * {
 *     double data;
 * }
 * </pre>
 */
class ControlPacket : public ::omnetpp::cPacket
{
  protected:
    double data = 0;

  private:
    void copy(const ControlPacket& other);

  protected:
    bool operator==(const ControlPacket&) = delete;

  public:
    ControlPacket(const char *name=nullptr, short kind=0);
    ControlPacket(const ControlPacket& other);
    virtual ~ControlPacket();
    ControlPacket& operator=(const ControlPacket& other);
    virtual ControlPacket *dup() const override {return new ControlPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getData() const;
    virtual void setData(double data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ControlPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ControlPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ControlPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<ControlPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CONTROLPACKET_M_H

