//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/TimerNextPacket.msg.
//

#ifndef __TIMERNEXTPACKET_M_H
#define __TIMERNEXTPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TimerNextPacket;
/**
 * Class generated from <tt>messages/TimerNextPacket.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message TimerNextPacket
 * {
 *     int target;
 *     double lambda;
 * }
 * </pre>
 */
class TimerNextPacket : public ::omnetpp::cMessage
{
  protected:
    int target = 0;
    double lambda = 0;

  private:
    void copy(const TimerNextPacket& other);

  protected:
    bool operator==(const TimerNextPacket&) = delete;

  public:
    TimerNextPacket(const char *name=nullptr, short kind=0);
    TimerNextPacket(const TimerNextPacket& other);
    virtual ~TimerNextPacket();
    TimerNextPacket& operator=(const TimerNextPacket& other);
    virtual TimerNextPacket *dup() const override {return new TimerNextPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTarget() const;
    virtual void setTarget(int target);

    virtual double getLambda() const;
    virtual void setLambda(double lambda);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TimerNextPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TimerNextPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TimerNextPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<TimerNextPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TIMERNEXTPACKET_M_H

